[tool.poetry]
name = "babel"
version = "0.1.0"
description = ""
authors = ["Roberto Infante <roberto.infante03@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"
flask = "^3.1.0"
numpy = "^2.2.3"
scipy = "^1.15.2"
python-dotenv = "^1.0.1"
google-genai = "^1.5.0"
torch = "^2.6.0"
pyro-ppl = "^1.9.1"


[tool.poetry.group.dev.dependencies]
pytest = "^8.3.5"
pytest-cov = "^6.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
