[tool.poetry]
name = "bayesbraingpt"
version = "0.1.0"
description = ""
authors = ["Roberto Infante <roberto.infante03@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"
numpy = "^2.2.3"
scipy = "^1.15.2"
google = "^3.0.0"
python-dotenv = "^1.0.1"
google-genai = "^1.3.0"
torch = "^2.2.1"
pyro-ppl = "^1.9.0"
pytest = "^8.3.5"

[tool.poetry.group.dev.dependencies]
pytest = "^8.1.1"
pytest-cov = "^4.1.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
